### ISSUE TITLE
Try removing the extra `authorizeRequests` 

### ISSUE THREAD

**Issue by AndrewBell** [landongw/b-plate#2]
I don't believe you should need the configuration here on 93-95, as you already define your authorization patters above. I'm not sure this is the issue, but it could be causing odd behavior.

```
            .and()
            .authorizeRequests()
                .anyRequest().authenticated()
```

https://github.com/landongw/b-plate/blob/0df11eecbc5e378ec3c621edafbb70449b6dcc0e/src/main/java/com/wiedenman/b_plate/config/SecurityConfig.java#L94

**Comment by landongw** [comment]
Got it, thank you.  I removed those lines.  Same behavior.
